pkgs:
  - bash-completion
  - cron
  - curl
  - fd-find
  - ffmpeg
  - fzf
  - git
  - htop
  - jq
  - kitty-terminfo
  - nfs-common
  - pipx
  - ripgrep
  - rsync
  - sysstat
  - ufw
  - unattended-upgrades
  - va-driver-all
  - valkey-tools
  - vim
  - wireguard
